/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static pharmacy.management.system.DBProvider.add;
import static pharmacy.management.system.DBProvider.check;
import static pharmacy.management.system.DBProvider.closeConnect;
import static pharmacy.management.system.DBProvider.excuteAdd;
import static pharmacy.management.system.DBProvider.excuteCheck;
import static pharmacy.management.system.DBProvider.getConnect;
import static pharmacy.management.system.DBProvider.rs;

/**
 *
 * @author HOANG
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmpassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbfullname = new javax.swing.JLabel();
        lbusername = new javax.swing.JLabel();
        lbpass = new javax.swing.JLabel();
        lbconfirm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("Username:");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("Password:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("Confirm Password:");

        txtPassword.setToolTipText("");
        txtPassword.setPreferredSize(new java.awt.Dimension(6, 28));

        txtConfirmpassword.setToolTipText("");
        txtConfirmpassword.setPreferredSize(new java.awt.Dimension(6, 28));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setText("Full name:");

        txtFullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 102));
        jLabel9.setText("@2021 - Nguyen Minh Hoang");

        btnCancel.setBackground(new java.awt.Color(0, 153, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(0, 153, 102));
        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Splash-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbfullname.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbfullname.setForeground(new java.awt.Color(255, 51, 0));
        lbfullname.setText(" ");

        lbusername.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbusername.setForeground(new java.awt.Color(255, 51, 0));
        lbusername.setText(" ");

        lbpass.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbpass.setForeground(new java.awt.Color(255, 51, 0));
        lbpass.setText(" ");

        lbconfirm.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbconfirm.setForeground(new java.awt.Color(255, 51, 0));
        lbconfirm.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbfullname)
                            .addComponent(lbusername)
                            .addComponent(lbpass)
                            .addComponent(lbconfirm)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnCancel)
                        .addGap(38, 38, 38)
                        .addComponent(btnRegister)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbfullname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lbusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbconfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnRegister))
                .addGap(9, 9, 9)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        Signin l = new Signin();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    String url = "jdbc:mysql://localhost:3306/pharmacydb";
    String username_db = "root";
    String password_db = "";
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if (txtFullname.getText().equals("") && txtUsername.getText().equals("") && txtPassword.getText().equals("") && txtConfirmpassword.getText().equals("")) {
            lbfullname.setText("Please type your Fullname!");
            lbusername.setText("Please type your Username!");
            lbpass.setText("Please type your Password!");
            lbconfirm.setText("Please type your Confirmpassword!");
            txtFullname.requestFocus();
            //txtUsername.setText("");           
        } else if (txtUsername.getText().equals("") && txtPassword.getText().equals("") && txtConfirmpassword.getText().equals("")) {
            lbusername.setText("Please type your Username!");
            lbpass.setText("Please type your Password!");
            lbconfirm.setText("Please type your Confirmpassword!");
            txtUsername.requestFocus();
            lbfullname.setText("");
        } else if (txtFullname.getText().equals("") && txtPassword.getText().equals("") && txtConfirmpassword.getText().equals("")) {
            lbfullname.setText("Please type your Fullname!");
            lbpass.setText("Please type your Password!");
            lbconfirm.setText("Please type your Confirmpassword!");
            txtUsername.requestFocus();
            lbusername.setText("");
        } else if (txtFullname.getText().equals("") && txtUsername.getText().equals("") && txtConfirmpassword.getText().equals("")) {
            lbfullname.setText("Please type your Fullname!");
            lbusername.setText("Please type your Username!");
            lbconfirm.setText("Please type your Confirmpassword!");
            txtPassword.requestFocus();
            lbpass.setText("");
        } else if (txtFullname.getText().equals("") && txtUsername.getText().equals("") && txtPassword.getText().equals("")) {
            lbfullname.setText("Please type your Fullname!");
            lbusername.setText("Please type your Username!");
            lbpass.setText("Please type your Password!");
            txtFullname.requestFocus();
            lbconfirm.setText("");
        } else if (txtPassword.getText().equals("") && txtConfirmpassword.getText().equals("")) {
            lbpass.setText("Please type your Password!");
            lbconfirm.setText("Please type your Confirmpassword!");
            txtPassword.setText("");
            lbfullname.setText("");
            lbusername.setText("");
        } else if (txtFullname.getText().equals("") && txtPassword.getText().equals("")) {
            lbfullname.setText("Please type your Fullname!");
            lbpass.setText("Please type your Password!");
            txtFullname.requestFocus();
            lbusername.setText("");
            lbconfirm.setText("");
        } else if (txtFullname.getText().equals("") && txtUsername.getText().equals("")) {
            lbfullname.setText("Please type your Fullname!");
            lbusername.setText("Please type your Username!");
            txtFullname.requestFocus();
            lbpass.setText("");
            lbconfirm.setText("");
        } else if (txtFullname.getText().equals("") && txtConfirmpassword.getText().equals("")) {
            lbfullname.setText("Please type your Fullname!");
            lbconfirm.setText("Please type your Confirmpassword!");
            txtFullname.requestFocus();
            lbusername.setText("");
            lbpass.setText("");
        } else if (txtUsername.getText().equals("") && txtPassword.getText().equals("")) {
            lbusername.setText("Please type your Username!");
            lbpass.setText("Please type your Password!");
            txtUsername.requestFocus();
            lbfullname.setText("");
            lbconfirm.setText("");
        } else if (txtUsername.getText().equals("") && txtConfirmpassword.getText().equals("")) {
            lbusername.setText("Please type your Username!");
            lbconfirm.setText("Please type your Confirmpassword!");
            txtUsername.requestFocus();
            lbfullname.setText("");
            lbpass.setText("");
        } else if (txtFullname.getText().equals("")) {
            lbfullname.setText("Please type your Username!");
            txtFullname.requestFocus();
            lbusername.setText("");
            lbpass.setText("");
            lbconfirm.setText("");
        } else if (txtUsername.getText().equals("")) {
            lbusername.setText("Please type your Username!");
            txtUsername.requestFocus();
            lbfullname.setText("");
            lbpass.setText("");
            lbconfirm.setText("");
        } else if (txtPassword.getText().equals("")) {
            lbpass.setText("Please type your Confirmpassword!");
            txtPassword.requestFocus();
            lbfullname.setText("");
            lbusername.setText("");
            lbconfirm.setText("");
        } else if (txtConfirmpassword.getText().equals("")) {
            lbconfirm.setText("Please type your Password!");
            txtPassword.requestFocus();
            lbfullname.setText("");
            lbusername.setText("");
            lbpass.setText("");
        } else {
            if (txtPassword.getText().equals(txtConfirmpassword.getText()) == false) {
                lbconfirm.setText("Password does not match!");
                txtConfirmpassword.requestFocus();
            } else {
                try {
                    getConnect();
                    //Connection conn = DriverManager.getConnection(url, username_db, password_db);
                    //PreparedStatement add = conn.prepareStatement("insert into nv (full_name, user_name, pwd) values (?,?,?)");
                    String sql_add ="insert into nv (full_name, user_name, pwd) values (?,?,?)";
                    excuteAdd(sql_add);
                    //PreparedStatement check = conn.prepareStatement("select * from nv where user_name=?");
                    String sql_check = "select * from nv where user_name=?";
                    excuteCheck(sql_check);
                    check.setString(1, txtUsername.getText());
                    add.setString(1, txtFullname.getText());
                    add.setString(2, txtUsername.getText());
                    add.setString(3, txtPassword.getText());
                    rs = check.executeQuery();
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Account have already!");
                    } else {
                        int row = add.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Register account successful!");
                        Signin l = new Signin();
                        l.setVisible(true);
                        this.dispose();
                    }
                    //conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            closeConnect();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbconfirm;
    private javax.swing.JLabel lbfullname;
    private javax.swing.JLabel lbpass;
    private javax.swing.JLabel lbusername;
    private javax.swing.JPasswordField txtConfirmpassword;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
