/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy.management.system;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import static pharmacy.management.system.DBProvider.add;
import static pharmacy.management.system.DBProvider.check;
import static pharmacy.management.system.DBProvider.closeConnect;
import static pharmacy.management.system.DBProvider.excuteAdd;
import static pharmacy.management.system.DBProvider.excuteCheck;
import static pharmacy.management.system.DBProvider.excuteGet;
import static pharmacy.management.system.DBProvider.excuteSQL;
import static pharmacy.management.system.DBProvider.excuteUpdate_Delete;
import static pharmacy.management.system.DBProvider.get;
import static pharmacy.management.system.DBProvider.getConnect;
import static pharmacy.management.system.DBProvider.rs;
import static pharmacy.management.system.DBProvider.rs1;
import static pharmacy.management.system.DBProvider.rs2;
import static pharmacy.management.system.DBProvider.stt;

/**
 *
 * @author HOANG
 */
public class StartScreenUser extends javax.swing.JFrame {

    /**
     * Creates new form StartScreenUser
     */
    public StartScreenUser() {
        initComponents();
        SelectMed();
        SelectCus();
        SelectMan();
        SelectRepo();
        cbxCpndata();
        jdateCurrentMedi();
        jdateCurrentCus();
        txtDateReport.disable();
        jdateCurrentReport();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPharma = new javax.swing.JTabbedPane();
        pnlCustomer = new javax.swing.JPanel();
        headingCus = new javax.swing.JLabel();
        pnlButtonCus = new javax.swing.JPanel();
        btnAddCus = new javax.swing.JButton();
        btnUpdateCus = new javax.swing.JButton();
        btnDeleteCus = new javax.swing.JButton();
        btnClearCus = new javax.swing.JButton();
        pnlCusInfo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCusID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCusAdd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCusPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dateCusBirth = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCus = new javax.swing.JTable();
        pnlMedicine = new javax.swing.JPanel();
        headingCus1 = new javax.swing.JLabel();
        pnlButtonMed = new javax.swing.JPanel();
        btnAddMed = new javax.swing.JButton();
        btnUpdateMed = new javax.swing.JButton();
        btnDeleteMed = new javax.swing.JButton();
        btnClearMed = new javax.swing.JButton();
        pnlInforMed = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMedID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMedUnit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMedAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMedExists = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateFab = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dateExp = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cbxCompany = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMedi = new javax.swing.JTable();
        pnlManufactor = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pnlManuInfo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtManuID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtManuName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtManuAdd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtManuExp = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtManuPhone = new javax.swing.JTextField();
        pnlButtonManu = new javax.swing.JPanel();
        btnAddManu = new javax.swing.JButton();
        btnUpdateManu = new javax.swing.JButton();
        btnDeleteManu = new javax.swing.JButton();
        btnClearManu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbManu = new javax.swing.JTable();
        pnlReport = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlReportInfo = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtReportID = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtEmID = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtCuID = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtRepoTotal = new javax.swing.JTextField();
        txtDateReport = new javax.swing.JTextField();
        pnlButtonReport = new javax.swing.JPanel();
        btnAddRepo = new javax.swing.JButton();
        btnUpdateRepo = new javax.swing.JButton();
        btnDeleteRepo = new javax.swing.JButton();
        btnReportDetail = new javax.swing.JButton();
        btnClearRepo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbReport = new javax.swing.JTable();
        mbPharma = new javax.swing.JMenuBar();
        mSystem = new javax.swing.JMenu();
        btnSignOut = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();
        mUser = new javax.swing.JMenu();
        btnUserInfo = new javax.swing.JMenuItem();
        btnChangePassword = new javax.swing.JMenuItem();
        mAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy Management System");

        tpPharma.setBackground(new java.awt.Color(255, 255, 255));
        tpPharma.setFocusable(false);
        tpPharma.setName(""); // NOI18N

        pnlCustomer.setBackground(new java.awt.Color(255, 255, 255));

        headingCus.setBackground(new java.awt.Color(102, 102, 0));
        headingCus.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        headingCus.setForeground(new java.awt.Color(0, 153, 102));
        headingCus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingCus.setText("MANAGE CUSTOMER");

        pnlButtonCus.setBackground(new java.awt.Color(255, 255, 255));

        btnAddCus.setText("Add");
        btnAddCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCusActionPerformed(evt);
            }
        });
        pnlButtonCus.add(btnAddCus);

        btnUpdateCus.setText("Update");
        btnUpdateCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCusActionPerformed(evt);
            }
        });
        pnlButtonCus.add(btnUpdateCus);

        btnDeleteCus.setText("Delete");
        btnDeleteCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCusActionPerformed(evt);
            }
        });
        pnlButtonCus.add(btnDeleteCus);

        btnClearCus.setText("Clear");
        btnClearCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCusActionPerformed(evt);
            }
        });
        pnlButtonCus.add(btnClearCus);

        pnlCusInfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Customer ID:");

        jLabel11.setText("Name:");

        jLabel12.setText("Address:");

        jLabel13.setText("Phone:");

        txtCusPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusPhoneActionPerformed(evt);
            }
        });
        txtCusPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCusPhoneKeyTyped(evt);
            }
        });

        jLabel14.setText("Birthday:");

        dateCusBirth.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout pnlCusInfoLayout = new javax.swing.GroupLayout(pnlCusInfo);
        pnlCusInfo.setLayout(pnlCusInfoLayout);
        pnlCusInfoLayout.setHorizontalGroup(
            pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCusInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCusInfoLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateCusBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCusInfoLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCusPhone))
                    .addGroup(pnlCusInfoLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCusAdd))
                    .addGroup(pnlCusInfoLayout.createSequentialGroup()
                        .addGroup(pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCusName)
                            .addGroup(pnlCusInfoLayout.createSequentialGroup()
                                .addComponent(txtCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCusInfoLayout.setVerticalGroup(
            pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCusInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCusAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(dateCusBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        tbCus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbCusMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tbCus);

        javax.swing.GroupLayout pnlCustomerLayout = new javax.swing.GroupLayout(pnlCustomer);
        pnlCustomer.setLayout(pnlCustomerLayout);
        pnlCustomerLayout.setHorizontalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingCus, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlButtonCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCustomerLayout.setVerticalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingCus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerLayout.createSequentialGroup()
                        .addComponent(pnlCusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlButtonCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tpPharma.addTab("Customer", pnlCustomer);

        pnlMedicine.setBackground(new java.awt.Color(255, 255, 255));

        headingCus1.setBackground(new java.awt.Color(102, 102, 0));
        headingCus1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        headingCus1.setForeground(new java.awt.Color(0, 153, 102));
        headingCus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingCus1.setText("MANAGE MEDICINE");

        pnlButtonMed.setBackground(new java.awt.Color(255, 255, 255));

        btnAddMed.setText("Add");
        btnAddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedActionPerformed(evt);
            }
        });
        pnlButtonMed.add(btnAddMed);

        btnUpdateMed.setText("Update");
        btnUpdateMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMedActionPerformed(evt);
            }
        });
        pnlButtonMed.add(btnUpdateMed);

        btnDeleteMed.setText("Delete");
        btnDeleteMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMedActionPerformed(evt);
            }
        });
        pnlButtonMed.add(btnDeleteMed);

        btnClearMed.setText("Clear");
        btnClearMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearMedActionPerformed(evt);
            }
        });
        pnlButtonMed.add(btnClearMed);

        pnlInforMed.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Medicine ID:");

        txtMedID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedIDKeyTyped(evt);
            }
        });

        jLabel2.setText("Name:");

        jLabel3.setText("Unit Price:");

        txtMedUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedUnitKeyTyped(evt);
            }
        });

        jLabel4.setText("Amount:");

        txtMedAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedAmountKeyTyped(evt);
            }
        });

        jLabel5.setText("Exists:");

        txtMedExists.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedExistsKeyTyped(evt);
            }
        });

        jLabel6.setText("Fab:");

        dateFab.setDateFormatString("yyyy-MM-dd");

        jLabel7.setText("Exp:");

        dateExp.setDateFormatString("yyyy-MM-dd");

        jLabel8.setText("Company:");

        javax.swing.GroupLayout pnlInforMedLayout = new javax.swing.GroupLayout(pnlInforMed);
        pnlInforMed.setLayout(pnlInforMedLayout);
        pnlInforMedLayout.setHorizontalGroup(
            pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInforMedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInforMedLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateFab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInforMedLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInforMedLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInforMedLayout.createSequentialGroup()
                        .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInforMedLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMedUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInforMedLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInforMedLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMedExists, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInforMedLayout.createSequentialGroup()
                                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMedName, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(txtMedID))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlInforMedLayout.setVerticalGroup(
            pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInforMedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMedUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMedExists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dateFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dateExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInforMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbMedi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMediMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMedi);

        javax.swing.GroupLayout pnlMedicineLayout = new javax.swing.GroupLayout(pnlMedicine);
        pnlMedicine.setLayout(pnlMedicineLayout);
        pnlMedicineLayout.setHorizontalGroup(
            pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingCus1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMedicineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlButtonMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInforMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMedicineLayout.setVerticalGroup(
            pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingCus1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMedicineLayout.createSequentialGroup()
                        .addComponent(pnlInforMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlButtonMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tpPharma.addTab("Medicine", pnlMedicine);

        pnlManufactor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setBackground(new java.awt.Color(102, 102, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("MANAGE MANUFACTOR");

        pnlManuInfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Manufactor ID:");

        jLabel18.setText("Name:");

        jLabel19.setText("Address:");

        jLabel20.setText("Experiences:");

        jLabel21.setText("Phone:");

        txtManuPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtManuPhoneKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlManuInfoLayout = new javax.swing.GroupLayout(pnlManuInfo);
        pnlManuInfo.setLayout(pnlManuInfoLayout);
        pnlManuInfoLayout.setHorizontalGroup(
            pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtManuPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(txtManuExp)
                    .addComponent(txtManuAdd)
                    .addComponent(txtManuName)
                    .addComponent(txtManuID))
                .addContainerGap())
        );
        pnlManuInfoLayout.setVerticalGroup(
            pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtManuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtManuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtManuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtManuExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlManuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtManuPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pnlButtonManu.setBackground(new java.awt.Color(255, 255, 255));

        btnAddManu.setText("Add");
        btnAddManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddManuActionPerformed(evt);
            }
        });
        pnlButtonManu.add(btnAddManu);

        btnUpdateManu.setText("Update");
        btnUpdateManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateManuActionPerformed(evt);
            }
        });
        pnlButtonManu.add(btnUpdateManu);

        btnDeleteManu.setText("Delete");
        btnDeleteManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteManuActionPerformed(evt);
            }
        });
        pnlButtonManu.add(btnDeleteManu);

        btnClearManu.setText("Clear");
        btnClearManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearManuActionPerformed(evt);
            }
        });
        pnlButtonManu.add(btnClearManu);

        tbManu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbManu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbManuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbManu);

        javax.swing.GroupLayout pnlManufactorLayout = new javax.swing.GroupLayout(pnlManufactor);
        pnlManufactor.setLayout(pnlManufactorLayout);
        pnlManufactorLayout.setHorizontalGroup(
            pnlManufactorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManufactorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManufactorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlManuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlButtonManu, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlManufactorLayout.setVerticalGroup(
            pnlManufactorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManufactorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pnlManufactorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlManufactorLayout.createSequentialGroup()
                        .addComponent(pnlManuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlButtonManu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tpPharma.addTab("Manufactor", pnlManufactor);

        pnlReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MANAGE REPORT");

        pnlReportInfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setText("Report ID:");

        jLabel32.setText("Date:");

        jLabel33.setText("Empployee ID:");

        jLabel34.setText("Customer ID:");

        jLabel35.setText("Total:");

        javax.swing.GroupLayout pnlReportInfoLayout = new javax.swing.GroupLayout(pnlReportInfo);
        pnlReportInfo.setLayout(pnlReportInfoLayout);
        pnlReportInfoLayout.setHorizontalGroup(
            pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCuID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtReportID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDateReport, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRepoTotal))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlReportInfoLayout.setVerticalGroup(
            pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtReportID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtDateReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtEmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtCuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlReportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtRepoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnlButtonReport.setBackground(new java.awt.Color(255, 255, 255));

        btnAddRepo.setText("Add");
        btnAddRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRepoActionPerformed(evt);
            }
        });
        pnlButtonReport.add(btnAddRepo);

        btnUpdateRepo.setText("Update");
        btnUpdateRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRepoActionPerformed(evt);
            }
        });
        pnlButtonReport.add(btnUpdateRepo);

        btnDeleteRepo.setText("Delete");
        btnDeleteRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRepoActionPerformed(evt);
            }
        });
        pnlButtonReport.add(btnDeleteRepo);

        btnReportDetail.setText("Details");
        pnlButtonReport.add(btnReportDetail);

        btnClearRepo.setText("Clear");
        btnClearRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearRepoActionPerformed(evt);
            }
        });
        pnlButtonReport.add(btnClearRepo);

        tbReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReportMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbReport);

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportLayout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlReportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlButtonReport, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addComponent(pnlReportInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlButtonReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tpPharma.addTab("Report", pnlReport);

        mbPharma.setBackground(new java.awt.Color(255, 255, 255));
        mbPharma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mSystem.setText("System");

        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        mSystem.add(btnSignOut);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        mSystem.add(btnExit);

        mbPharma.add(mSystem);

        mUser.setText("Account");

        btnUserInfo.setText("Account Info");
        btnUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserInfoActionPerformed(evt);
            }
        });
        mUser.add(btnUserInfo);

        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        mUser.add(btnChangePassword);

        mbPharma.add(mUser);

        mAbout.setText("About ");
        mAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mAboutMouseClicked(evt);
            }
        });
        mAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAboutActionPerformed(evt);
            }
        });
        mbPharma.add(mAbout);

        setJMenuBar(mbPharma);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpPharma)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpPharma)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void SelectMed() {
        String sql = "select a.med_id, a.med_name, a.med_unitprice, a.med_amount, a.med_exists, a.med_fab, a.med_exp, b.man_name from medicine a, manufactor b where a.man_id = b.man_id";
        dataTable(sql, tbMedi);
    }

    public void SelectCus() {
        String sql = "select * from customer";
        dataTable(sql, tbCus);
    }

    public void SelectMan() {
        String sql = "select * from manufactor";
        dataTable(sql, tbManu);
    }

    public void SelectRepo() {
        String sql = "select * from report";
        dataTable(sql, tbReport);
    }

    public void dataTable(String sql, JTable tb) {
        getConnect();
        excuteSQL(sql);
        tb.setModel(DbUtils.resultSetToTableModel((rs)));
        closeConnect();
    }

    public void jdateCurrentMedi() {
        long millis = System.currentTimeMillis();
        java.sql.Date date = new java.sql.Date(millis);
        dateExp.setDate(date);
        dateFab.setDate(date);

    }

    public void jdateCurrentCus() {
        long millis = System.currentTimeMillis();
        java.sql.Date date = new java.sql.Date(millis);
        dateCusBirth.setDate(date);
    }
    String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
    public void jdateCurrentReport() {
        txtDateReport.setText(timeStamp);
    }
    public void cbxCpndata() {
        try {
            getConnect();
            String sql = "select DISTINCT man_name from manufactor";
            excuteSQL(sql);
            while (rs.next()) {
                cbxCompany.addItem(rs.getString("man_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        closeConnect();
    }

    java.util.Date dateEx, dateFa, dateBi, dateCus;
    java.sql.Date MyFab, MyExp, emp_birth, cus_birth;
    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        Signin si = new Signin();
        si.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserInfoActionPerformed
        // TODO add your handling code here:
        UserInfo ui = new UserInfo();
        ui.setVisible(true);
    }//GEN-LAST:event_btnUserInfoActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        ChangePass cp = new ChangePass();
        cp.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void mAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAboutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mAboutActionPerformed

    private void btnAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedActionPerformed
        // TODO add your handling code here:
        dateFa = dateExp.getDate();
        MyFab = new java.sql.Date(dateFa.getTime());
        dateEx = dateFab.getDate();
        MyExp = new java.sql.Date(dateEx.getTime());
        if (txtMedID.getText().equals("") || txtMedName.getText().equals("") || txtMedUnit.getText().equals("") || txtMedAmount.getText().equals("") || txtMedExists.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Sonething is empty!");
        } else {
            try {
                int man_id = 0;
                getConnect();
                String med_name = "";
                String man_name_check = "";
                String sql_add = "insert into medicine values (?,?,?,?,?,?,?,?)";
                String get_id = "select man_id from manufactor where man_name=?";
                excuteAdd(sql_add);
                excuteGet(get_id);
                get.setString(1, cbxCompany.getSelectedItem().toString());
                rs2 = get.executeQuery();
                if (rs2.next()) {
                    man_id = rs2.getInt("man_id");
                }
                String sql_check = "select med_name from medicine where med_name = ?";
                excuteCheck(sql_check);
                check.setString(1, txtMedName.getText());
                rs1 = check.executeQuery();
                if (rs1.next()) {
                    JOptionPane.showMessageDialog(this, "Medicine have already exists!");
                } else {

                    try {
                        add.setInt(1, Integer.valueOf(txtMedID.getText()));
                        add.setString(2, txtMedName.getText());
                        add.setInt(3, Integer.valueOf(txtMedUnit.getText()));
                        add.setInt(4, Integer.valueOf(txtMedAmount.getText()));
                        add.setInt(5, Integer.valueOf(txtMedExists.getText()));
                        add.setDate(6, MyFab);
                        add.setDate(7, MyExp);
                        add.setInt(8, man_id);
                        int row = add.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Add successful!");
                        SelectMed();
                    } catch (SQLException ex) {
                        Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        closeConnect();
    }//GEN-LAST:event_btnAddMedActionPerformed

    private void btnUpdateMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMedActionPerformed
        // TODO add your handling code here:
        if (txtMedID.getText().equals("") || txtMedName.getText().equals("") || txtMedUnit.getText().equals("") || txtMedAmount.getText().equals("") || txtMedExists.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Something is empty");
        } else {
            try {
                int man_id = 0;
                dateFa = dateExp.getDate();
                MyFab = new java.sql.Date(dateFa.getTime());
                dateEx = dateFab.getDate();
                MyExp = new java.sql.Date(dateEx.getTime());
                getConnect();
                String get_id = "select man_id from manufactor where man_name=?";
                excuteGet(get_id);
                get.setString(1, cbxCompany.getSelectedItem().toString());
                rs = get.executeQuery();

                if (rs.next()) {
                    man_id = rs.getInt("man_id");
                }
                String sql = "update medicine set med_name ='" + txtMedName.getText() + "', med_unitprice=" + txtMedUnit.getText() + ", med_amount=" + txtMedAmount.getText() + ", med_exists = '" + txtMedExists.getText() + "', med_fab='" + MyFab + "',med_exp='" + MyExp + "',man_id=" + man_id + " where med_id=" + txtMedID.getText() + "";
                excuteUpdate_Delete(sql);
                JOptionPane.showMessageDialog(this, "Updated Success");
                SelectMed();
            } catch (SQLException ex) {
                Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        closeConnect();
    }//GEN-LAST:event_btnUpdateMedActionPerformed

    private void btnDeleteMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMedActionPerformed
        // TODO add your handling code here:
        if (txtMedID.getText().equals("") || txtMedName.getText().equals("") || txtMedUnit.getText().equals("") || txtMedAmount.getText().equals("") || txtMedExists.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Somthing has been empty!");
        } else {
            getConnect();
            String sql = "delete from medicine where med_id=" + txtMedID.getText() + "";
            excuteUpdate_Delete(sql);
            SelectMed();
            JOptionPane.showMessageDialog(this, "Delete success");
        }
        closeConnect();
        btnClearMedActionPerformed(evt);
    }//GEN-LAST:event_btnDeleteMedActionPerformed

    private void btnClearMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMedActionPerformed
        // TODO add your handling code here:
        txtMedID.setText("");
        txtMedName.setText("");
        txtMedUnit.setText("");
        txtMedAmount.setText("");
        jdateCurrentMedi();
        cbxCompany.setSelectedIndex(0);
        txtMedExists.setText("");
    }//GEN-LAST:event_btnClearMedActionPerformed

    private void txtMedIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedIDKeyTyped

    private void txtMedUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedUnitKeyTyped
        // TODO add your handling code here:
        char char_input = evt.getKeyChar();
        if (!Character.isDigit(char_input) && (char_input != '\b')) {
            JOptionPane.showMessageDialog(this, "Only Positive Numbers Allowed");
            txtMedUnit.requestFocus();
        }
    }//GEN-LAST:event_txtMedUnitKeyTyped

    private void txtMedAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedAmountKeyTyped
        // TODO add your handling code here:
        char char_input = evt.getKeyChar();
        if (!Character.isDigit(char_input) && (char_input != '\b')) {
            JOptionPane.showMessageDialog(this, "Only Positive Numbers Allowed");
            txtMedAmount.requestFocus();
        }
    }//GEN-LAST:event_txtMedAmountKeyTyped

    private void txtMedExistsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedExistsKeyTyped
        // TODO add your handling code here:
        char char_input = evt.getKeyChar();
        if (!Character.isDigit(char_input) && (char_input != '\b')) {
            JOptionPane.showMessageDialog(this, "Only Positive Numbers Allowed");
            txtMedExists.requestFocus();
        }
    }//GEN-LAST:event_txtMedExistsKeyTyped

    private void tbMediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMediMouseClicked
        try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) tbMedi.getModel();
            int Myindex = tbMedi.getSelectedRow();
            txtMedID.setText(model.getValueAt(Myindex, 0).toString());
            txtMedName.setText(model.getValueAt(Myindex, 1).toString());
            txtMedUnit.setText(model.getValueAt(Myindex, 2).toString());
            txtMedAmount.setText(model.getValueAt(Myindex, 3).toString());
            txtMedExists.setText(model.getValueAt(Myindex, 4).toString());
            Date dateF = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(Myindex, 5).toString());
            dateExp.setDate(dateF);
            Date dateE = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(Myindex, 6).toString());
            dateFab.setDate(dateE);
            String company = model.getValueAt(Myindex, 7).toString();
            cbxCompany.setSelectedItem(company);
        } catch (ParseException ex) {
            Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbMediMouseClicked

    private void btnAddCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCusActionPerformed
        // TODO add your handling code here:
        if (txtCusName.getText().equals("") || txtCusAdd.getText().equals("") || txtCusPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Somthing is empty!");
        } else {
            try {
                String cus_name = "", cus_phone = "";
                dateCus = dateCusBirth.getDate();
                cus_birth = new java.sql.Date(dateCus.getTime());
                getConnect();
                String sql_add = "insert into customer values (?,?,?,?,?)";
                String sql_check = "select * from customer where cus_name=?";
                excuteAdd(sql_add);
                excuteCheck(sql_check);
                check.setString(1, txtCusName.getText());
                rs = check.executeQuery();
                if (rs.next()) {
                    cus_name = rs.getString("cus_name");
                    cus_phone = rs.getString("cus_phone");
                }
                if ((txtCusName.getText().equals(cus_name) == true) && (txtCusPhone.getText().equals(cus_phone) == true)) {
                    JOptionPane.showMessageDialog(this, "Customer have already!");
                } else {
                    add.setInt(1, Integer.valueOf(txtCusID.getText()));
                    add.setString(2, txtCusName.getText());
                    add.setString(3, txtCusAdd.getText());
                    add.setString(4, txtCusPhone.getText());
                    add.setDate(5, cus_birth);
                    int row = add.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Add successful!");
                    SelectCus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        closeConnect();
    }//GEN-LAST:event_btnAddCusActionPerformed

    private void btnUpdateCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCusActionPerformed
        // TODO add your handling code here:
        if (txtCusID.getText().equals("") || txtCusName.getText().equals("") || txtCusAdd.getText().equals("") || txtCusPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Something has been empty!");
        } else {
            dateCus = dateCusBirth.getDate();
            cus_birth = new java.sql.Date(dateCus.getTime());
            getConnect();
            String sql = "update customer set cus_name='" + txtCusName.getText() + "',cus_add='" + txtCusAdd.getText() + "',cus_phone='" + txtCusPhone.getText() + "',cus_birtday='" + cus_birth + "' where cus_id=" + txtCusID.getText() + "";
            excuteUpdate_Delete(sql);
            JOptionPane.showMessageDialog(this, "Updated Success");
            SelectCus();
        }
        closeConnect();
    }//GEN-LAST:event_btnUpdateCusActionPerformed

    private void btnDeleteCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCusActionPerformed
        // TODO add your handling code here:
        if (txtCusID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Somthing has been empty!");
        } else {
            getConnect();
            String sql = "delete from customer where cus_id=" + txtCusID.getText() + "";
            excuteUpdate_Delete(sql);
            JOptionPane.showMessageDialog(this, "Delete success");
            SelectCus();
        }
        closeConnect();
        btnClearCusActionPerformed(evt);
    }//GEN-LAST:event_btnDeleteCusActionPerformed

    private void btnClearCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCusActionPerformed
        // TODO add your handling code here:
        txtCusID.setText("");
        txtCusName.setText("");
        txtCusAdd.setText("");
        txtCusPhone.setText("");
        jdateCurrentCus();
    }//GEN-LAST:event_btnClearCusActionPerformed

    private void txtCusPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusPhoneActionPerformed

    private void txtCusPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusPhoneKeyTyped
        // TODO add your handling code here:
        char char_input = evt.getKeyChar();
        if (!Character.isDigit(char_input) && (char_input != '\b')) {
            JOptionPane.showMessageDialog(this, "Only Positive Numbers Allowed");
            txtCusPhone.requestFocus();
        }
    }//GEN-LAST:event_txtCusPhoneKeyTyped

    private void tbCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCusMouseClicked
        try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) tbCus.getModel();
            int Myindex = tbCus.getSelectedRow();
            txtCusID.setText(model.getValueAt(Myindex, 0).toString());
            txtCusName.setText(model.getValueAt(Myindex, 1).toString());
            txtCusAdd.setText(model.getValueAt(Myindex, 2).toString());
            txtCusPhone.setText(model.getValueAt(Myindex, 3).toString());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(Myindex, 4).toString());
            dateCusBirth.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbCusMouseClicked

    private void tbCusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCusMouseEntered

    private void txtManuPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManuPhoneKeyTyped
        // TODO add your handling code here:
        char char_input = evt.getKeyChar();
        if (!Character.isDigit(char_input) && (char_input != '\b')) {
            JOptionPane.showMessageDialog(this, "Only Positive Numbers Allowed");
            txtManuPhone.requestFocus();
        }
    }//GEN-LAST:event_txtManuPhoneKeyTyped

    private void btnAddManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddManuActionPerformed
        // TODO add your handling code here:
        if (txtManuID.getText().equals("") || txtManuName.getText().equals("") || txtManuAdd.getText().equals("") || txtManuExp.getText().equals("") || txtManuPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ID is empty!");
        } else {
            try {
                getConnect();
                String sql_add = "insert into manufactor values (?,?,?,?,?)";
                String sql_check = "select * from manufactor where man_name=?";
                excuteAdd(sql_add);
                excuteCheck(sql_check);
                check.setString(1, txtManuName.getText());
                rs = check.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Manufactor have already!");
                } else {
                    add.setInt(1, Integer.valueOf(txtManuID.getText()));
                    add.setString(2, txtManuName.getText());
                    add.setString(3, txtManuAdd.getText());
                    add.setString(4, txtManuExp.getText());
                    add.setString(5, txtManuPhone.getText());
                    int row = add.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Add successful!");
                    SelectMan();
                }
            } catch (SQLException ex) {
                Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        closeConnect();
    }//GEN-LAST:event_btnAddManuActionPerformed

    private void btnUpdateManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateManuActionPerformed
        // TODO add your handling code here:
        if (txtManuID.getText().equals("") || txtManuName.getText().equals("") || txtManuAdd.getText().equals("") || txtManuExp.getText().equals("") || txtManuPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Something wrong");
        } else {
            getConnect();
            String sql = "update manufactor set man_name='" + txtManuName.getText() + "',man_add='" + txtManuAdd.getText() + "',man_exp='" + txtManuExp.getText() + "',man_phone='" + txtManuPhone.getText() + "' where man_id=" + txtManuID.getText() + "";
            excuteUpdate_Delete(sql);
            JOptionPane.showMessageDialog(this, "Updated Success");
            SelectMan();
        }
        closeConnect();
    }//GEN-LAST:event_btnUpdateManuActionPerformed

    private void btnDeleteManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteManuActionPerformed
        // TODO add your handling code here:
        if (txtManuID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Somthing has been empty!");
        } else {
            getConnect();
            String sql = "delete from manufactor where man_id=" + txtManuID.getText() + "";
            excuteUpdate_Delete(sql);
            JOptionPane.showMessageDialog(this, "Delete success");
            SelectMan();
        }
        closeConnect();
        btnClearManuActionPerformed(evt);
    }//GEN-LAST:event_btnDeleteManuActionPerformed

    private void btnClearManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearManuActionPerformed
        // TODO add your handling code here:
        txtManuID.setText("");
        txtManuName.setText("");
        txtManuAdd.setText("");
        txtManuExp.setText("");
        txtManuPhone.setText("");
    }//GEN-LAST:event_btnClearManuActionPerformed

    private void tbManuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbManuMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbManu.getModel();
        int Myindex = tbManu.getSelectedRow();
        txtManuID.setText(model.getValueAt(Myindex, 0).toString());
        txtManuName.setText(model.getValueAt(Myindex, 1).toString());
        txtManuAdd.setText(model.getValueAt(Myindex, 2).toString());
        txtManuExp.setText(model.getValueAt(Myindex, 3).toString());
        txtManuPhone.setText(model.getValueAt(Myindex, 4).toString());
    }//GEN-LAST:event_tbManuMouseClicked

    private void mAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mAboutMouseClicked
        // TODO add your handling code here:
        About a = new About();
        a.setVisible(true);
    }//GEN-LAST:event_mAboutMouseClicked

    private void tbReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReportMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbReport.getModel();
        int Myindex = tbReport.getSelectedRow();
        txtReportID.setText(model.getValueAt(Myindex, 0).toString());
        String dateR = model.getValueAt(Myindex, 1).toString();
//        String[] parts = dateR.split(" ");
//        String parts1 = parts[0];
//        String parts2 = parts[1];
//        String[] part = parts2.split(":");
//        String part1 = part[0];
//        String part2 = part[1];
//        String part3 = part[2];
        //            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(parts1);
//            dateReport.setDate(date);
        txtDateReport.setText(dateR);
//        txtHH.setText(part1);
//        txtMM.setText(part2);
//        txtSS.setText(part3);
        txtEmID.setText(model.getValueAt(Myindex, 2).toString());
        txtCuID.setText(model.getValueAt(Myindex, 3).toString());
        txtRepoTotal.setText(model.getValueAt(Myindex, 4).toString());
    }//GEN-LAST:event_tbReportMouseClicked

    private void btnUpdateRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRepoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "User has not permision");
    }//GEN-LAST:event_btnUpdateRepoActionPerformed

    private void btnDeleteRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRepoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "User has not permision");
    }//GEN-LAST:event_btnDeleteRepoActionPerformed

    private void btnClearRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearRepoActionPerformed
        // TODO add your handling code here:
        
        txtReportID.setText("");
        txtEmID.setText("");
        txtCuID.setText("");
        txtRepoTotal.setText("");
        //txtHH.setText("");
    }//GEN-LAST:event_btnClearRepoActionPerformed

    private void btnAddRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRepoActionPerformed
         // TODO add your handling code here:
         if (txtReportID.getText().equals("") || txtEmID.getText().equals("") || txtCuID.getText().equals("") || txtRepoTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Something is empty!");
        } else {
            try {
//                dateR = dateReport.getDate();
//                report_date = new java.sql.Date(dateR.getTime());
                getConnect();
                String sql_add = "insert into report values (?,?,?,?,?)";
                String sql_check = "select * from report where report_id=?";
                excuteAdd(sql_add);
                excuteCheck(sql_check);
                check.setInt(1, Integer.valueOf(txtReportID.getText()));
                rs = check.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Report have already!");
                } else {
                    add.setInt(1, Integer.valueOf(txtReportID.getText()));
                    add.setString(2, timeStamp);
                    add.setInt(3, Integer.valueOf(txtEmID.getText()));
                    add.setInt(4, Integer.valueOf(txtCuID.getText()));
                    add.setInt(5, Integer.valueOf(txtRepoTotal.getText()));                  
                    int row = add.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Add successful!");
                    SelectRepo();
                }
            } catch (SQLException ex) {
                Logger.getLogger(StartScreenAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        closeConnect();
    }//GEN-LAST:event_btnAddRepoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreenUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCus;
    private javax.swing.JButton btnAddManu;
    private javax.swing.JButton btnAddMed;
    private javax.swing.JButton btnAddRepo;
    private javax.swing.JMenuItem btnChangePassword;
    private javax.swing.JButton btnClearCus;
    private javax.swing.JButton btnClearManu;
    private javax.swing.JButton btnClearMed;
    private javax.swing.JButton btnClearRepo;
    private javax.swing.JButton btnDeleteCus;
    private javax.swing.JButton btnDeleteManu;
    private javax.swing.JButton btnDeleteMed;
    private javax.swing.JButton btnDeleteRepo;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JButton btnReportDetail;
    private javax.swing.JMenuItem btnSignOut;
    private javax.swing.JButton btnUpdateCus;
    private javax.swing.JButton btnUpdateManu;
    private javax.swing.JButton btnUpdateMed;
    private javax.swing.JButton btnUpdateRepo;
    private javax.swing.JMenuItem btnUserInfo;
    private javax.swing.JComboBox<String> cbxCompany;
    private com.toedter.calendar.JDateChooser dateCusBirth;
    private com.toedter.calendar.JDateChooser dateExp;
    private com.toedter.calendar.JDateChooser dateFab;
    private javax.swing.JLabel headingCus;
    private javax.swing.JLabel headingCus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenu mAbout;
    private javax.swing.JMenu mSystem;
    private javax.swing.JMenu mUser;
    private javax.swing.JMenuBar mbPharma;
    private javax.swing.JPanel pnlButtonCus;
    private javax.swing.JPanel pnlButtonManu;
    private javax.swing.JPanel pnlButtonMed;
    private javax.swing.JPanel pnlButtonReport;
    private javax.swing.JPanel pnlCusInfo;
    public static javax.swing.JPanel pnlCustomer;
    private javax.swing.JPanel pnlInforMed;
    private javax.swing.JPanel pnlManuInfo;
    private javax.swing.JPanel pnlManufactor;
    private javax.swing.JPanel pnlMedicine;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlReportInfo;
    private javax.swing.JTable tbCus;
    private javax.swing.JTable tbManu;
    private javax.swing.JTable tbMedi;
    private javax.swing.JTable tbReport;
    public static javax.swing.JTabbedPane tpPharma;
    private javax.swing.JTextField txtCuID;
    private javax.swing.JTextField txtCusAdd;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtCusPhone;
    private javax.swing.JTextField txtDateReport;
    private javax.swing.JTextField txtEmID;
    private javax.swing.JTextField txtManuAdd;
    private javax.swing.JTextField txtManuExp;
    private javax.swing.JTextField txtManuID;
    private javax.swing.JTextField txtManuName;
    private javax.swing.JTextField txtManuPhone;
    private javax.swing.JTextField txtMedAmount;
    private javax.swing.JTextField txtMedExists;
    private javax.swing.JTextField txtMedID;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtMedUnit;
    private javax.swing.JTextField txtRepoTotal;
    private javax.swing.JTextField txtReportID;
    // End of variables declaration//GEN-END:variables
}
